In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
import os

In [2]:
from featureExtraction import featureExtraction

In [3]:
def loadImages(img_dir):
    img_names = os.listdir(img_dir)
    img_list = []
    # Load images
    for img_name in img_names:
        img = cv.imread(img_dir + img_name)
        img_list.append(img)

    return img_list

    

In [4]:
img_dir = "./data/building/"
img_list = loadImages(img_dir)


In [5]:
fe = featureExtraction(img_list, k=2, method="FLANN", match_threshold=100)

In [6]:
adj = fe.run()
print(adj)

[[0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]]
